#!/bin/bash

init_variables() {
  BR_NORM='\e[00m'
  BR_RED='\e[00;31m'
  BR_GREEN='\e[00;32m'
  BR_YELLOW='\e[00;33m'
  BR_BLUE='\e[00;34m'
  BR_MAGENTA='\e[00;35m'
  BR_CYAN='\e[00;36m'
}

clear
init_variables

show_summary() {
echo "Backup Folder = $BRFOLDER
Include Home Directory = $BRhome"

if [ $BRhome = "n" ]; then
  echo "Keep home's hidden files and folders = $BRhidden"
fi

if [ $BRtar = "y" ]; then
  echo "Fefora detected: --acls --selinux --xattrs options activated"
fi
}

run_tar() {
  BR_TAROPTS="--sparse --exclude=/run/* --exclude=/dev/* --exclude=/proc/* --exclude=/lost+found --exclude=/sys/* --exclude=/media/* --exclude=/tmp/* --exclude=/mnt/* --exclude=.gvfs --exclude=${BRFOLDER}"
  if [ ${BRhome} = "n" ]; then
    BR_TAROPTS="${BR_TAROPTS} --exclude=/home/*"
  fi
  if [ ${BRtar} = "y" ]; then
    BR_TAROPTS="${BR_TAROPTS} --acls --selinux --xattrs"
  fi

  echo "==>Creating archive..."
  tar cvpf  "$BRFile".tar  ${BR_TAROPTS}   / 2>>"$BRFOLDER"/errors | tee "$BRFOLDER"/log

  if [ $BRhidden = "y" ]; then
    echo "==>Locating hidden files and folders inside /home, please wait..."
    find /home -maxdepth 1 -print | xargs tar rpvf "$BRFile".tar --no-recursion 2>>"$BRFOLDER"/errors | tee "$BRFOLDER"/log
    find /home -maxdepth 2 -name ".*" -print0 | xargs -0 tar rpvf "$BRFile".tar 2>>"$BRFOLDER"/errors | tee "$BRFOLDER"/log
  fi

  echo "==>Compressing archive..."
  gzip "$BRFile".tar
}

BRargs=`getopt -o "i:d:hn" -l "interface:,directory:,exclude-home,no-hidden,help" -n "$1" -- "$@"`

if [ $? -ne 0 ]; then
  echo "See $0 --help"
  exit
fi

eval set -- "$BRargs";

while true; do
  case "$1" in
    -i|--interface)
      BRinterface=$2
      shift 2
    ;;
    -d|--directory)
      BRFOLDER=$2
      shift 2
    ;;
    -h|--exclude-home)
      BRhome="n"
      shift
    ;;
    -n|--no-hidden)
      BRhidden="n"
      shift
    ;;
    --help)
      echo "
-i, --interface         interface to use
-d, --directory		path for backup folder
-h, --exclude-home	exclude /home
-n  --no-hidden         dont keep home's hidden files and folders

--help	print this page
"
      exit
      shift
    ;;
    --)
      shift
      break
    ;;
  esac
done

if [ $(id -u) -gt 0 ]; then
  echo -e "${BR_RED}Script must run as root${BR_NORM}"
  exit
fi

if [ -f /etc/fedora-release ]; then
  BRtar="y"
else
  BRtar="n"
fi

PS3="Choice: "
interfaces=(CLI Dialog)

while [ -z "$BRinterface" ]; do
  echo -e "\n${BR_CYAN}Select interface or enter Q to quit${BR_NORM}"
  select c in ${interfaces[@]}; do
    if [ $REPLY = "q" ] || [ $REPLY = "Q" ]; then
      echo -e "${BR_YELLOW}Aborted by User${BR_NORM}"
      exit
    elif [[ $REPLY = [0-9]* ]] && [ $REPLY -gt 0 ] && [ $REPLY -le ${#interfaces[@]} ]; then
      BRinterface=$c
      break
    else
      echo -e "${BR_RED}Please select a valid option from the list or enter Q to quit${BR_NORM}"
    fi
  done
done

if [ $BRinterface = "CLI" ]; then
  clear
  if [ -z "$BRFOLDER" ]; then
    echo "This script will make a tar backup image of your entire system."
    echo -e "\n==>Make sure you have enough free space."
    echo -e "\n==>Also make sure you have GRUB or SYSLINUX packages installed."
    echo -e "\n${BR_YELLOW}GRUB Packages:${BR_NORM}"
    echo "Arch: grub-bios"
    echo "Debian: grub-pc"
    echo "Fedora: grub2"
    echo -e "\n${BR_YELLOW}SYSLINUX Packages:${BR_NORM}"
    echo "Arch: syslinux"
    echo "Debian: syslinux extlinux"
    echo "Fedora: syslinux syslinux-extlinux"
    echo -e "\n${BR_CYAN}Press ENTER to continue.${BR_NORM}"
    read -s a
    clear
  fi

  if [ ! -d "$BRFOLDER" ] && [ -n "$BRFOLDER" ]; then
    echo -e "${BR_RED}Directory does not exist${BR_NORM}"
    unset BRFOLDER
  fi

  while [ -z "$BRFOLDER" ]; do
    echo -e "\n${BR_CYAN}The default folder for creating the backup file is / (root)\nDo you want to save in the default folder?${BR_NORM}"
    read -p "(Y/n): " an

    if [ -n "$an" ]; then
      def=$an
    else
      def="y"
    fi

    if [ $def = "y" ] || [ $def = "Y" ]; then
      BRFOLDER="/"
    elif [ $def = "n" ] || [ $def = "N" ]; then
      while [  -z "$BRFOLDER" ] || [ ! -d "$BRFOLDER" ]; do
        echo -e "\n${BR_CYAN}Insert the folder path where the backup will be created${BR_NORM}"
        read -p "Path: " BRFOLDER
        if [ ! -d "$BRFOLDER" ]; then
          echo -e "${BR_RED}Directory does not exist.${BR_NORM}"
        fi
      done
    else
      echo -e "${BR_RED}Please enter a valid option${BR_NORM}"
    fi
  done

  while [ -z "$BRhome" ] ; do
    echo -e "\n${BR_CYAN}Do you want to include /home?${BR_NORM}"
    read -p "(Y/n):" an

    if [ -n "$an" ]; then
      def=$an
    else
      def="y"
    fi

    if [ $def = "y" ] || [ $def = "Y" ]; then
      BRhome="y"
    elif [ $def = "n" ] || [ $def = "N" ]; then
      BRhome="n"
    else
      echo -e "${BR_RED}Please enter a valid option${BR_NORM}"
    fi
  done

  if [ $BRhome = "n" ]; then
    while [ -z "$BRhidden" ] ; do
      echo -e "\n${BR_CYAN}Do you want to keep hidden files and folders inside /home?${BR_NORM}"
      read -p "(Y/n):" an

      if [ -n "$an" ]; then
        def=$an
      else
        def="y"
      fi

      if [ $def = "y" ] || [ $def = "Y" ]; then
        BRhidden="y"
      elif [ $def = "n" ] || [ $def = "N" ]; then
        BRhidden="n"
      else
        echo -e "${BR_RED}Please enter a valid option${BR_NORM}"
      fi
    done
  fi

  echo -e "\n${BR_GREEN}SUMMARY${BR_NORM}"
  show_summary

  while [ -z "$BRcontinue" ]; do
    echo -e "\n${BR_CYAN}Do you want continue?${BR_NORM}"
    read -p "(Y/n):" an

    if [ -n "$an" ]; then
      def=$an
    else
      def="y"
    fi

    if [ $def = "y" ] || [ $def = "Y" ]; then
      BRcontinue="y"
    elif [ $def = "n" ] || [ $def = "N" ]; then
      BRcontinue="n"
      echo -e "${BR_YELLOW}Aborted by User${BR_NORM}"
      exit
    else
      echo -e "${BR_RED}Please enter a valid option${BR_NORM}"
    fi
  done

  if [  "x$BRcontinue" = "xy" ]; then
    BRFOLDER_IN=(`echo ${BRFOLDER}/$(date +%A-%d-%m-%Y) | sed 's://*:/:g'`)
    BRFOLDER="${BRFOLDER_IN[@]}"

    echo "==>Preparing..."
    mkdir -p "$BRFOLDER"
    touch "$BRFOLDER"/log
    touch "$BRFOLDER"/errors
    sleep 1

    echo "==>Creating backup image, please wait..."
    BRFile="$BRFOLDER"/Backup-"`date +%A-%d-%m-%Y-%T`"
    sleep 1

    run_tar

    echo "==>Setting permissions"
    chmod ugo+rw -R "$BRFOLDER" 2>> "$BRFOLDER"/errors
    echo -e "${BR_CYAN}Completed. Backup image and logs saved in $BRFOLDER.${BR_NORM}"
  fi

elif [ $BRinterface = "Dialog" ]; then
  if [ -z $(which dialog 2> /dev/null) ];then
    echo -e "${BR_RED}Package dialog is not installed\n${BR_CYAN}Install the package and re-run the script${BR_NORM}"
    exit
  fi

  if [ -z "$BRFOLDER" ]; then
    dialog --no-ok --title "Info" --msgbox  "This script will make a tar backup image of your entire system.

==>Make sure you have enough free space.

==>Make sure you have GRUB or SYSLINUX packages installed.

GRUB Packages:
-->Arch: grub-bios
-->Debian: grub-pc
-->Fedora: grub2

SYSLINUX Packages:
-->Arch: syslinux
-->Debian: syslinux extlinux
-->Fedora: syslinux syslinux-extlinux

Press OK to continue." 22 70
  fi

  if [ ! -d "$BRFOLDER" ] &&  [ -n "$BRFOLDER" ]; then
    echo "Directory does not exist." | dialog --progressbox "ERROR" 30 70
    sleep 2
    unset BRFOLDER
  fi

  while [ -z "$BRFOLDER" ]; do
    dialog --title "Message" --yesno "The default folder for creating the backup file is / (root). Do you want to save in the default folder?" 8 50
    if [ $? = "0" ]; then
      BRFOLDER="/"
    else
      while [  -z "$BRFOLDER" ] || [ ! -d "$BRFOLDER" ]; do
        exec 3>&1
        BRFOLDER=$(dialog  --no-cancel --inputbox "Insert the folder path where the backup will be created" 8 50 2>&1 1>&3)
        if [ ! -d "$BRFOLDER" ]; then
          echo "Directory does not exist." | dialog --progressbox "ERROR" 30 70
          sleep 2
        fi
      done
    fi
  done

  while [ -z "$BRhome" ]; do
    dialog --title "Message"  --yesno "Do you want to include /home?" 8 50
    if [ $? = "0" ]; then
      BRhome="y"
    else
      BRhome="n"
    fi
  done

  if [ $BRhome = "n" ]; then
    while [ -z "$BRhidden" ] ; do
      dialog --title "Message"  --yesno "Do you want to keep hidden files and folders inside /home?" 8 50
      if [ $? = "0" ]; then
        BRhidden="y"
      else
        BRhidden="n"
      fi
    done
  fi

  dialog --title "Summary"  --yesno "`show_summary`
------------------------------------
Press Yes to continue or No to abort." 13 50

  if [ $? = "1" ]; then
    exit
  fi

  BRFOLDER_IN=(`echo ${BRFOLDER}/$(date +%A-%d-%m-%Y) | sed 's://*:/:g'`)
  BRFOLDER="${BRFOLDER_IN[@]}"

  mkdir -p "$BRFOLDER"
  touch "$BRFOLDER"/log
  touch "$BRFOLDER"/errors
  sleep 1

  BRFile="$BRFOLDER"/Backup-"`date +%A-%d-%m-%Y-%T`"

  run_tar | dialog --progressbox "Creating backup image..." 30 70

  chmod ugo+rw -R "$BRFOLDER" 2>> "$BRFOLDER"/errors
  dialog --title "Info" --msgbox  "Completed. Backup image and logs saved in $BRFOLDER" 8 50
else
  echo -e "${BR_RED}Wrong interface name:${BR_NORM} $BRinterface\n${BR_CYAN}Available options: CLI Dialog${BR_NORM}"
fi
