'\" t
.\"		Title: system-tar-and-restore
.\"    Author: [ see the "Authors" section]
.\"    Manual: system-tar-and-restore Manual
.\"    Source: system-tar-and-restore 3.6.4
.\"  Language: English
.TH "system-tar-and-restore" "1" "11 Aug 2013" "3\&.6.4" "General Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://github.com/tritonas00/system-tar-and-restore
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" -----------------------------------------------------------------
.\" * set default formatting 
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH NAME
System tar & restore \- Backup and Restore your system using tar or Transfer it with rsync\&.
.SH SYNOPSIS
.sp
\fIbackup.sh\fR [options]
.sp
\fIrestore.sh\fR [options]
.SH DESCRIPTION
.sp
System tar & restore contains two bash scripts, \fIbackup.sh\fR and \fIrestore.sh\fR\&.
.sp
The purpose is to make the process of backing up and restoring a full GNU/Linux installation 
easier, using tar or transfer an existing installation using rsync.
.sp
Supported distributions: 
.B Arch, 
.B Debian, 
.B Fedora
.SH BACKUP DESCRIPTION
.sp
Backup script makes a tar backup of \fI/\fR in a given location\&. It will make a folder 
in that location which contains the \fBarchive\fR and the \fBlog\fR file "backup.log" 
(usefull for tracking tar errors/warnings)\&.
.SH BACKUP OPERATIONS
.PP
\fB\-i, \-\-interface\fR
.RS 4
interface to use (cli dialog)
.RE
.PP
\fB\-N, \-\-no-color\fR
.RS 4
disable colors
.RE
.PP
\fB\-d, \-\-directory\fR
.RS 4
backup folder path\&. Default path is \fI/\fR
.RE
.PP
\fB\-h, \-\-exclude-home\fR
.RS 4
exclude \fI/home\fR directory (keep hidden files and folders)
.RE
.PP
\fB\-n, \-\-no-hidden\fR
.RS 4
dont keep home's hidden files and folders (use with -h)
.RE
.PP
\fB\-a, \-\-archiver\fR
.RS 4
select archiver\&: tar and bsdtar are supported
.RE
.PP
\fB\-c, \-\-compression\fR
.RS 4
compression type\&: gzip and xz are supported
.RE
.PP
\fB\-u, \-\-user-options\fR
.RS 4
additional tar options (See tar --help or man bsdtar) 
.RE
.PP
\fB\-\-help\fR
.RS 4
show all arguments
.RE
.SH RESTORE DESCRIPTION
.sp
User must create and format partitions using his favorite partition manager 
before running the script. At least one \fI/\fR \fB(root)\fR partition is 
required and optionally a seperate partition for \fI/home\fR, \fI/boot\fR
and a \fIswap\fR partition\&.
.sp
Restore script contains two modes: \fBRestore\fR and \fBTransfer\fR\&.In 
\fBRestore Mode\fR\&, the script uses the above created archive to extract it 
in user defined partitions\&. In \fBTransfer Mode\fR\&, the script uses 
\fBRSYNC\fR to transfer the root filesystem \fI/\fR in user defined partitions\&.
Then generates fstab\&, rebuilds initramfs image for every available kernel\&, 
re-generates locales, installs and auto-configures Grub or Syslinux in MBR 
of given device and finally unmounts and cleans everything\&.
.sp
log file is saved as /tmp/restore.log
.SH RESTORE OPERATIONS
.PP
\fB\-i, \-\-interface\fR
.RS 4
interface to use (cli dialog)
.RE
.PP
\fB\-N, \-\-no\-color\fR
.RS 4
disable colors
.RE
.PP
\fB\-q, \-\-quiet\fR
.RS 4
dont ask, just run 
.RE
.PP
\fB\-t, \-\-transfer\fR
.RS 4
activate tranfer mode 
.RE
.PP
\fB\-o, \-\-only-hidden\fR
.RS 4
transfer /home's hidden files and folders only 
.RE
.PP
\fB\-r, \-\-root\fR
.RS 4
target root partition
.RE
.PP
\fB\-h, \-\-home\fR
.RS 4
target home partition
.RE
.PP
\fB\-b, \-\-boot\fR
.RS 4
target boot partition
.RE
.PP
\fB\-c, \-\-custom-partitions\fR
.RS 4
specify custom partitions (mountpoint=device e.g /usr=/dev/sda3 /var/cache=/dev/sda4)
.RE
.PP
\fB\-s, \-\-swap\fR
.RS 4
swap partition
.RE
.PP
\fB\-m, \-\-mount-options\fR
.RS 4
comma-separated list of mount options (root partition)
.RE
.PP
\fB\-g, \-\-grub\fR
.RS 4
target disk for grub
.RE
.PP
\fB\-S, \-\-syslinux\fR
.RS 4
target disk for syslinux
.RE
.PP
\fB\-k, \-\-kernel-options\fR
.RS 4
additional kernel options (syslinux)
.RE
.PP
\fB\-f, \-\-file\fR
.RS 4
backup file path
.RE
.PP
\fB\-u, \-\-url\fR
.RS 4
url
.RE
.PP
\fB\-n, \-\-username\fR
.RS 4
username
.RE
.PP
\fB\-p, \-\-password\fR
.RS 4
password
.RE
.PP
\fB\-a, \-\-archiver\fR
.RS 4
select the archiver you used to create the backup archive (tar bsdtar)
.RE
.PP
\fB\-R, \-\-rootsubvolname\fR
.RS 4
subvolume name for root
.RE
.PP
\fB\-H, \-\-homesubvol\fR
.RS 4
make subvolume for 
\fI/home\fR
.RE
.PP
\fB\-V, \-\-varsubvol\fR
.RS 4
make subvolume for \fI/var\fR
.RE
.PP
\fB\-U, \-\-usrsubvol\fR
.RS 4
make subvolume for \fI/usr\fR
.RE
.PP
\fB\-\-help\fR
.RS 4
show all arguments
.RE
.SH NOTES
.sp
The system that runs the restore script and the target system (the one you 
want to restore)\&, must have the same architecture (for \fIchroot\fR to work)\&.
.sp
For booting a \fBBTRFS\fR subvolumed root successfully with \fBSyslinux\fR\&,
it is recommended to have a seperate \fI/boot\fR partition\&. Recommended 
subvolume name is: __active. 
.sp
When using \fBLVM\fR\&, it is also recommended to have a seperate 
\fI/boot\fR partition\&. 
.sp
When using \fBRAID\fR\&, it is recommended to create a seperate raid1 array with 
metadata=1.0 as your \fI/boot\fR partition\&. 
.sp
When using \fBGRUB with BIOS and GPT\fR\& you must create a \fIBIOS Boot Partition:\fR 
~1 MiB unformatted partition with bios_grub flag enabled (0xEF02 for gdisk).
.sp
In the target system, in case of \fBSyslinux\fR\&, old /boot/syslinux/syslinux.cfg
is saved as /boot/syslinux.cfg-old\&.
.sp
In the target system, if distribution is \fBFedora\fR\& and \fBGrub\fR\& is selected\&, old 
/etc/default/grub is saved as /etc/default/grub-old\&.
.SH EXAMPLES USING ARGUMENTS
.sp
Backup system in the directory \fI/home/john/\fR and use \fBGZIP\fR 
compression and \fBTAR\fR archiver:
.RS 4
\fB./backup.sh \-d /home/john/ \-c gzip -a tar\fR 
.RE
.sp
Backup system in the directory \fI/home/john/\fR\&, use \fBXZ\fR compression, 
\fBBSDTAR\fR archiver and exclude \fI/home/\fR directory from backup tarball:
.RS 4
\fB./backup.sh \-d /home/john/ \-c xz \-h \-n -a bsdtar\fR 
.RE
.sp
Backup system in the directory \fI/home/john/\fR\&, use \fBGZIP\fR compression, 
\fBTAR\fR archiver and keep only hidden files and folders from \fI/home/\fR: 
.RS 4
\fB./backup.sh \-d /home/john/ \-c gzip \-h -a tar\fR 
.RE
.sp
Restore system in  \fI/dev/sdb1\fR partition, using \fBgrub\fR as bootloader 
and use \fI/home/john/Downloads/backup.tar.gz\fR as local backup file:
.RS 4
\fB./restore.sh \-r /dev/sdb1 \-g /dev/sdb \-f /home/john/Downloads/backup.tar.gz -a tar\fR
.RE
.sp
Transfer running system using \fBrsync\fR\& in \fBssd\fR\&. The \fI/\fR partition will be
\fI/dev/sda1\fR, using \fBsyslinux\fR\& and \fBnomodeset\fR\& kernel option will be enabled:
.RS 4
\fB./restore.sh \-r /dev/sda1 \-S /dev/sda \-m discard,errors=remount-ro -S /dev/sda -k nomodeset -t\fR
.RE
.sp
Restore system in \fI/dev/sdb1\fR for \fI/\fR (root) partition\&, \fI/dev/sdb2\fR
for \fI/home\fR partition\&, \fI/dev/sdb3\fR for \fIswap\fR\& partition, using \fBsyslinux\fR 
as bootloader and downloading backup file from ftp server:
.RS 4
\fB./restore.sh \-r /dev/sdb1 \-h /dev/sdb2 \-s /dev/sdb3 \-S /dev/sdb \-u 
ftp://server/data/backup.tar.xz -a bsdtar\fR
.RE
.sp
Restore system in  \fI/dev/sdb2\fR for \fI/\fR (root) partition, \fI/dev/sdb1\fR
for \fI/boot\fR partition, \fI/dev/sdb3\fR for \fI/home\fR\&, using \fBsyslinux\fR 
as bootloader and downloading backup file from protected http server\&.
.RS 4
\fB./restore.sh \-r /dev/sdb2 \-b /dev/sdb1 \-h /dev/sdb3 \-S /dev/sdb \-u 
http://server/backup.tar.gz \-n user \-p pass -a tar\fR
.RE
.sp
Transfer running  system using \fBrsync\fR\&. The \fI/\fR partition will be
\fI/dev/mapper/debian-root\fR which is a \fBLVM\fR partition\&, \fI/dev/sdb1\fR
for \fI/boot\fR partition using \fBgrub\fR as bootloader:
.RS 4
\fB./restore.sh \-r /dev/mapper/debian\-root \-b /dev/sdb1 \-g /dev/sdb \-t -a tar\fR
.RE
.sp
Transfer running system using \fBrsync\fR\&. The \fI/\fR partition will be
\fI/dev/sda2\fR which is in \fBBTRFS\fR filesystem\&, \fI/dev/sda1\fR for
\fI/boot\fR partition\&, using \fBsyslinux\fR as bootloader\&.
The root will be in __active subvolume, \fI/usr\fR\&, \fI/var\fR\&,
\fI/home\fR will also be in subvolumes and btrfs compression will be enabled:
.RS 4
\fB./restore.sh \-t \-b /dev/sda1 \-r /dev/sda2 \-m compress=lzo \-S /dev/sda \-R __active \-V \-U \-H\fR
.RE
.sp
Restore system in \fBRAID\fR partitions\&. The boot partition will be \fI/dev/md0\fR
and the root partition will be \fI/dev/md1\fR\&. The backup will be the local file
\fI/home/john/Downloads/backup.tar.gz\fR and \fBsyslinux\fR will be installed in all disks that array \fI/dev/md0\fR\ contains:
.RS 4
\fB./restore.sh \-r /dev/md1 \-b /dev/md0 \-f /home/john/Downloads/backup.tar.gz \-S /dev/md0 -a bsdtar\fR
.RE
.SH LIMITATIONS
\fBUEFI\fR not supported - not tested
.SH ONLINE DOCUMENTATION
https://github.com/tritonas00/system-tar-and-restore#about
.SH BUGS
Report bugs in: https://github.com/tritonas00/system-tar-and-restore/issues
.SH AUTHOR
tritonas00 at gmail dot com
